[package]
name = "hexcede/runtime"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Future = "red-blox/future@1.0.1"
Observe = "4812571/observe@0.2.6"
Trove = "sleitnick/trove@1.4.0"
TableUtil = "sleitnick/table-util@1.2.1"